In [2]:
#matriz quadrada - nºlinhas=nºcolunas
#matriz transposta - linhas viram colunas, colunas viram linhas
#matriz identidade - a diagonal principal tem elementos iguais a 1

In [6]:
mat = [[5,4,7], [0,3,4], [0,0,6]]
for linha in mat:
    print(linha)

[5, 4, 7]
[0, 3, 4]
[0, 0, 6]


In [10]:
print(mat[0]) #cada indice é uma linha
print(mat[-1]) #ultima linha

[5, 4, 7]
[0, 0, 6]


In [13]:
#para acessar o 3, segunda linha segunda coluna
mat[1][1]

3

In [48]:
[linha[1] for linha in mat] #imprimir 2 coluna

[4, 3, 0]

In [50]:
# imprimindo a segunda coluna
print(mat) 
for i in mat:
    print(i[1]) #cada i é uma linha, entao eu imprimo sempre o segundo elemento de cada linha

[[5, 4, 7], [0, 3, 4], [0, 0, 6]]
4
3
0


In [ ]:
#UTILIZANDO NUMPY

In [17]:
import numpy as np

#simulando pontos em um jogo de basquete

joao_pts = [20,30,40,15]
pedro_pts = [100,24,48,23]
maria_pts = [92,22,34,12]
marcos_pts = [12,34,12,43]

In [20]:
pontos = np.array([joao_pts,pedro_pts,maria_pts,marcos_pts])
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [22]:
pontos[0] #pontos do jaoo

array([20, 30, 40, 15])

In [24]:
pontos[1,0] #2 linha 1 coluna

100

In [28]:
my_data = np.arange(0,20) #criar um array com valores entre 0-19
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [33]:
#transformar esse array em uma matriz 5x4

# reshape(lista, tupla), transforma uma lista em uma matriz tupla(linha x coluna)

mat1 = np.reshape(my_data, (5,4))
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [35]:
# quero o elemento 10, como faz?
mat1[2][2]

10

In [37]:
print(pontos)
pontos.item(5) #pego o valor na posicao 5(o indice vai da esquerda para direita, de cima para baixo)

[[ 20  30  40  15]
 [100  24  48  23]
 [ 92  22  34  12]
 [ 12  34  12  43]]


24

In [39]:
#utilizando python
m1 = ['python', 'eh', 'legal']
m2 = ['guido', 'van', 'rossum']
m3 = [10,20,30]

[m1,m2,m3]

[['python', 'eh', 'legal'], ['guido', 'van', 'rossum'], [10, 20, 30]]

In [41]:
#utilizando numpy
np.array([m1,m2,m3]) #dtype é o tipo do array, aqui é unicode

array([['python', 'eh', 'legal'],
       ['guido', 'van', 'rossum'],
       ['10', '20', '30']], dtype='<U6')