In [2]:
import numpy as np

In [7]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [9]:
np.insert(arr,1,10) # insere no array 'arr', posicao '1', valor '10'

array([ 1, 10,  2,  3])

In [12]:
a = np.array([[1,2], [3,4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


In [67]:
print(a.sum(axis=0)) # somar os elementos do primeiro eixo -> 1+3 e 2+4 (as colunas)

[4 6]


In [20]:
print(a.sum(axis=1)) # somar os elementos do segundo eixo -> 1+2 e 3+4 (as linhas)

[3 7]


In [22]:
np.insert(a,1,5,axis=1) # o eixo é um parametro opcional, que pode ser passado em matrizes com mais de 1 dimensao

array([[1, 5, 2],
       [3, 5, 4]])

In [27]:
np.insert(a,1,5,axis=0)

array([[1, 2],
       [5, 5],
       [3, 4]])

In [28]:
# Adicionar valores ao final da lista = metodo Append

In [33]:
# append retorna uma copia do array com os valores indexados
ex = np.array([1,2,3])
np.append(ex,4)

array([1, 2, 3, 4])

In [35]:
np.append(ex,[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [46]:
ex2 = np.array([[1,2],[3,4]])
np.append(ex2, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
print(np.append(ex2, np.array([5,6]).reshape(1,2), axis=0)) #adiciona uma linha
print(np.append(ex2, np.array([5,6]).reshape(2,1), axis=1)) #adiciona uma coluna

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
