In [3]:
import numpy as np

In [6]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [8]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
m2 / m1 # divisao cada elemento matriz

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [15]:
np.matrix.round(m2 / m1) #arredondar

array([[7., 4., 3.],
       [2., 2., 2.]])

In [17]:
10 * m2

array([[ 70,  80,  90],
       [100, 110, 120]])

In [19]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
m2 - 1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
m1 * m2 # multiplicacao de cada elemento matriz

array([[ 7, 16, 27],
       [40, 55, 72]])

In [28]:
m1 ** 2 # potencia de  cada elemento matriz

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [44]:
#COMO EU MULTIPLICO MATRIZES ENTAO????????

matriz1 = np.array([[1,2], [4,5]])
matriz2 = np.array([[6,7], [8,9]])
print(matriz1)
print(matriz2)

[[1 2]
 [4 5]]
[[6 7]
 [8 9]]


In [45]:
np.dot(matriz1, matriz2) #atraves da funcao dot

array([[22, 25],
       [64, 73]])