In [4]:
l = [20, 30, 10, 40, 50, 60, 70]
print(l[1:3])
print(l[::2]) #começa do indice 0, e vai de 2 em 2

[30, 10]
[20, 10, 50, 70]


In [7]:
#utilizando numpy
import numpy as np
a = np.array(l)
a

array([20, 30, 10, 40, 50, 60, 70])

In [10]:
print(a[1:3])
print(a[::2])

[30 10]
[20 10 50 70]


In [13]:
#utilizando python
l2 = l[:] #fazer uma copia, nao é o mesmo objeto
l2

[20, 30, 10, 40, 50, 60, 70]

In [15]:
l2[0] = 1000
print(l) #nao sofreu alteracoes
print(l2)

[20, 30, 10, 40, 50, 60, 70]
[1000, 30, 10, 40, 50, 60, 70]


In [17]:
#utilizando numpy
b = a[:] #dessa vez nao foi feito copia, apenas aponta para o mesmo endereço de memoria
b

array([20, 30, 10, 40, 50, 60, 70])

In [20]:
b[0] = 1000 #altera o 'a' tambem
print(a)
print(b)

[1000   30   10   40   50   60   70]
[1000   30   10   40   50   60   70]


In [22]:
b[:] = 42 #utilizar [:] significa todos elementos
b

array([42, 42, 42, 42, 42, 42, 42])

In [25]:
c = a.copy() #agora sim faremos copia
print(c)
print(a)

[42 42 42 42 42 42 42]
[42 42 42 42 42 42 42]


In [26]:
c[0] = 1000 #nao vai alterar o objeto a
print(c)
print(a)

[1000   42   42   42   42   42   42]
[42 42 42 42 42 42 42]
